04/08/2023

Var
// Seção de Declarações das variáveis 
unidade: inteiro
total:  real

Inicio
// programa de promoção
escreva ("Digite quantidade de trakinas que vc deseja comprar: ")
leia(unidade)
se (unidade < 11)entao
total <- unidade * 2.50
senao
total <- unidade *2.00
fimse

escreval ("voçê comprou ",unidade, "trakinas")
escreval(" voçê vao pagar o total de R$: ",total)


Fimalgoritmo